[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
shapely = "3ccHCxQuyua3zePL3t9Nu7p4CR27CaKasSctiA8Zh1sb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn tsx --test tests/*.ts"

[test]
startup_wait = 60000
shutdown_wait = 2000
upgradeable = false