[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
shapely = "3ccHCxQuyua3zePL3t9Nu7p4CR27CaKasSctiA8Zh1sb"

[programs.devnet]
shapely = "3ccHCxQuyua3zePL3t9Nu7p4CR27CaKasSctiA8Zh1sb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn tsx --test tests/*.ts"

[test]
startup_wait = 60000
shutdown_wait = 2000
upgradeable = false

[test.validator]
url = "https://api.mainnet-beta.solana.com"

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"