/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  isProgramError,
  type Address,
  type SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM,
  type SolanaError,
} from '@solana/kit';
import { SHAPELY_PROGRAM_ADDRESS } from '../programs';

/** CustomError: Custom error message */
export const SHAPELY_ERROR__CUSTOM_ERROR = 0x1770; // 6000

export type ShapelyError = typeof SHAPELY_ERROR__CUSTOM_ERROR;

let shapelyErrorMessages: Record<ShapelyError, string> | undefined;
if (process.env.NODE_ENV !== 'production') {
  shapelyErrorMessages = {
    [SHAPELY_ERROR__CUSTOM_ERROR]: `Custom error message`,
  };
}

export function getShapelyErrorMessage(code: ShapelyError): string {
  if (process.env.NODE_ENV !== 'production') {
    return (shapelyErrorMessages as Record<ShapelyError, string>)[code];
  }

  return 'Error message not available in production bundles.';
}

export function isShapelyError<TProgramErrorCode extends ShapelyError>(
  error: unknown,
  transactionMessage: {
    instructions: Record<number, { programAddress: Address }>;
  },
  code?: TProgramErrorCode
): error is SolanaError<typeof SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM> &
  Readonly<{ context: Readonly<{ code: TProgramErrorCode }> }> {
  return isProgramError<TProgramErrorCode>(
    error,
    transactionMessage,
    SHAPELY_PROGRAM_ADDRESS,
    code
  );
}
